### ISSUE TITLE
CommandEnv has been removed from markbates/refresh

### ISSUE THREAD

**Issue by 0xCMP** [volatiletech/abcweb#14]
See this commit: https://github.com/markbates/refresh/commit/25435da78dbf2fa5067f3c156051103ad72bce0e

I got an error building the `cmd/` folder

```bash
~/p/g/s/g/v/a/cmd ❯❯❯ go install ./
# github.com/volatiletech/abcweb/cmd
./dev.go:200: unknown field 'CommandEnv' in struct literal of type refresh.Configuration
```

**Comment by nullbio** [comment]
Replied in the PR. Thanks.

**Comment by nullbio** [comment]
This has been fixed in v3: https://github.com/volatiletech/abcweb/releases/tag/v3.0.0 -- please let me know if any problems persist, thank you.
