### ISSUE TITLE
abcweb migrate status error

### ISSUE THREAD

**Issue by fadeojo** [volatiletech/abcweb#22]
Mac OSX already has a `mig` (Mach Interface Generator tool) executable in `/usr/bin`. This hinders `abcweb` from installing and calling `volatiletech/mig`

```
> abcweb migrate status
error: cannot read file status
Error: exit status 1
Usage:
  abcweb migrate status [flags]

Flags:
  -h, --help   help for status

Global Flags:
      --db string    Valid options: postgres|mysql (default: "config.toml db field")
  -e, --env string   The config.toml file environment to load (default "dev")
```

**Comment by nullbio** [comment]
Hi @fadeojo -- If you ensure your GOPATH shows first in your PATH environment variable it should fix this problem.

**Comment by oadeojo** [comment]
@nullbio you solution worked great. I don't know if this is the best solution though.
